---
title: "Random Graphs"
author: "Cam"
date: "2023-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
options(scipen = 999)
```

Census API calls and cleaning
```{r, eval = F}
# first extract earliest (2010) data to initialize data frames
# later years will be appended to this
s0802_WA <- get_acs(geography = "state",
        table = "S0802",
        state = "WA",
        gemoetry = TRUE,
        survey = "acs1",
        year = 2010,
        cache_table = T) %>% 
  select(NAME, variable, estimate, moe) %>% 
  mutate(year = 2010) %>% 
  rename("location" = NAME)

s0802_sea <- get_acs(geography = "place",
        table = "S0802",
        state = "WA",
        gemoetry = TRUE,
        survey = "acs1",
        year = 2010,
        cache_table = T) %>% 
  filter(NAME == "Seattle city, Washington") %>% 
  select(NAME, variable, estimate, moe) %>% 
  mutate(year = 2010) %>% 
  rename("location" = NAME)

# appending years 2011-2022 
nums <- 2011:2022
# need to omit the year 2020 because the regular 1-year ACS for 2020 was not released and is not available in tidycensus.
nums <- nums[nums != 2020]

for (i in nums) {
  temp_WA <- get_acs(geography = "state",
        table = "S0802",
        state = "WA",
        gemoetry = TRUE,
        survey = "acs1",
        year = i,
        cache_table = T) %>% 
  select(NAME, variable, estimate, moe) %>% 
  mutate(year = i) %>% 
  rename("location" = NAME)
  s0802_WA <- rbind(s0802_WA, temp_WA)
  
  temp_sea <- get_acs(geography = "place",
        table = "S0802",
        state = "WA",
        gemoetry = TRUE,
        survey = "acs1",
        year = i,
        cache_table = T) %>% 
  filter(NAME == "Seattle city, Washington") %>% 
  select(NAME, variable, estimate, moe) %>% 
  mutate(year = i) %>% 
  rename("location" = NAME)
  s0802_sea <- rbind(s0802_sea, temp_sea)
}

# load the codebook for survey variables
s0802_keys <- load_variables(2022, "acs1/subject", cache = T) %>% filter(str_detect(name, "S0802"))
```

Further cleaning
```{r, eval = F}
# rename column so that it can be joined to s0802 table
# also separate out variable labels into multiple columns
s0802_keys <- s0802_keys %>% 
  select(name, label) %>% 
  rename("variable" = name) %>% 
  separate_wider_delim(cols = label, 
                       delim = "!!", 
                       names = c("trait1", "trait2", "trait3", "trait4", "trait5", "trait6"),
                       too_few = "align_start")

# combine Seattle and WA data, join keys
s0802 <- rbind(s0802_sea, s0802_WA) %>% left_join(s0802_keys)

# load the gas and collisions data
crash_sea <- read_delim("Data/Clean/seattle_collisions.csv")
crash_WA <- read_delim("Data/Clean/wa_collisions.csv")

gas_sea <- read_delim("Data/Clean/seattle_gas_dollars_per_gallon.csv")
gas_WA <- read_delim("Data/Clean/wa_gas_dollars_per_gallon.csv")

# add location variable to gas data so it can be joined
gas_sea <- gas_sea %>% mutate(location = "Seattle city, Washington")
gas_WA <- gas_WA %>% mutate(location = "Washington")

# join the data
gas <- rbind(gas_WA, gas_sea)

# tidy collision data from wide to long form
# need to be yearly, not monthly, tally up each column
crash_sea_yearly <- crash_sea %>% 
  pivot_longer(2:18, names_to = "year", values_to = "crashes") %>%
  group_by(year) %>% 
  summarize(total_crashes = sum(crashes)) %>% 
  mutate(location = "Seattle city, Washington", year = as.numeric(year))

crash_WA_yearly <- crash_WA %>% 
  pivot_longer(2:18, names_to = "year", values_to = "crashes") %>%
  group_by(year) %>% 
  summarize(total_crashes = sum(crashes)) %>% 
  mutate(location = "Washington", year = as.numeric(year))

# joining datasets
gas_and_crashes <- rbind(crash_WA_yearly, crash_sea_yearly) %>% 
  left_join(gas) %>% 
  rename("gas_price" = price)

final <- left_join(s0802, gas_and_crashes, by = c("year", "location"))

# save the final dataset
write.csv(final, "Data/Clean/final.csv", row.names = F)
```

Load final dataset
```{r}
final <- read_delim("Data/Clean/final.csv")
```


```{r}
final %>%
  mutate(trait5 = factor(trait5, levels = c("Less than 10 minutes", "10 to 14 minutes", "15 to 19 minutes", "20 to 24 minutes", "25 to 29 minutes", "30 to 34 minutes", "35 to 44 minutes", "45 to 59 minutes", "60 or more minutes"))) %>%
  filter(trait5 != "Mean travel time to work (minutes)", trait2 != "Total", trait4 == "TRAVEL TIME TO WORK") %>%
  group_by(trait5, trait2, location) %>%
  summarize(avg_estimate = mean(estimate),
            avg_moe = mean(moe)) %>%
  ggplot(aes(x = trait5, y = avg_estimate, fill = trait2)) +
  facet_wrap(~ location, scales = "free_y", ncol = 1) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = avg_estimate - avg_moe, ymax = avg_estimate + avg_moe), 
                position = position_dodge(width = 0.9),
                width = 0.25) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Travel Time vs Population", x = "Travel Time", y = "Percentage of Population", fill = "Mode of Transportation")
```

```{r}

```

